name: Build and Test
on: [push, pull_request]
jobs:
  moderate-modern:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.3', '7.4', '8.0', '8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: error_reporting=-1, display_errors=On
          coverage: none
      # 新增：安装GMSSL依赖
      - name: Install GMSSL
        run: |
          sudo apt update
          sudo apt install -y gcc make libssl-dev
          git clone https://github.com/guanzhi/GmSSL.git
          cd GmSSL && ./config && make && sudo make install
      - name: phpize
        run: phpize
        # 修改：指定GMSSL路径
      - name: configure
        run: ./configure --with-gmssl=/usr/local/gmssl
      - name: make
        run: make
      - name: test
        run: make test
